language: objective-c
osx_image: xcode9.2

script:
  - xcodebuild -scheme MathUtil -project MathUtil.xcodeproj -sdk iphonesimulator11.2 -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' build test
